name: 一键提取boot并修补

on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: 'ROM 下载直链'
        required: true
        default: 'https://mirrorbits.lineageos.org/full/tissot/20230328/lineage-19.1-20230328-nightly-tissot-signed.zip'

jobs:
  BootIMGExtractAction:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-pip
          sudo apt install unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack arj cabextract rename aria2
          sudo apt install liblzma-dev brotli lz4
          pip3 install backports.lzma protobuf pycrypto
          pip install protobuf==3.20
          BUILD_TIME=$(TZ=Asia/Shanghai date +"%m%d%H%M")
          echo "BUILD_TIME=$BUILD_TIME" >> $GITHUB_ENV
      - name: 提取镜像
        run: |
          cd ~
          git clone --recurse-submodules https://github.com/tosasitill/Firmware_extractor.git
          cd Firmware_extractor
          aria2c -s 10 -x 10 -d . -o firmware.zip "${{ github.event.inputs.rom_url }}"
          ./extractor.sh firmware.zip
          
      - name: 修补boot
        run: |
          cd ~
          git clone https://github.com/jax0ncai/Magisk_patche.git Magisk
          cd Magisk
          mv ~/Firmware_extractor/out/* ./
          mkdir done
          ./boot.sh

      - name: 上传到 Release
        uses: actions/upload-release-asset@v1
        with:
          url: ${{ env.RELEASE_URL }}
          asset_path: ~/Magisk/done/boot.img
          asset_name: boot-${{ env.BUILD_TIME }}.img
          asset_content_type: application/octet-stream
          token: ${{ secrets.GITHUB_TOKEN }}